// <auto-generated />
using HIMS_Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;


namespace HIMS_Web.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                
            modelBuilder.Entity("HIMS_Web.Models.Products", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("序号")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnName("产品名")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("location")
                        .HasColumnName("位置")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("type")
                        .HasColumnName("产品类型")
                        .HasColumnType("nvarchar(255)");

                        b.Property<string>("Owner")
                        .HasColumnName("店主")
                        .HasColumnType("nvarchar(32)");
                    
                    b.Property<double>("Price")
                        .HasColumnName("价格")
                        .HasColumnType("float");

                    b.HasKey("id");

                   
                    
                    b.ToTable("products");
                });
#pragma warning restore 612, 618
           
        }
    }
}
